# Generated by Django 5.0.6 on 2025-05-12 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessRegister_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_fname', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('owner_lname', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('company_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('contact_number', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('logo', models.FileField(blank=True, null=True, upload_to='profiles/')),
                ('website', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('address_line1', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('address_line2', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('address_line3', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('pin', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('location', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('district', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('state', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('active_status', models.BooleanField(default=True)),
                ('reg_date', models.DateField(auto_now_add=True)),
                ('company_code', models.CharField(default='COMID001', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='DistributorRegister_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('contact_no', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('agencies', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('profile', models.FileField(blank=True, null=True, upload_to='profiles/')),
                ('file', models.FileField(blank=True, null=True, upload_to='employee_files/')),
                ('address1', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('address2', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('address3', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('pin', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('location', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('district', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('state', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('active_status', models.BooleanField(default=False)),
                ('reg_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LogRegister_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_username', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('log_password', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('log_date', models.DateField(auto_now_add=True)),
                ('log_time', models.TimeField(auto_now_add=True)),
                ('position', models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Digital_Marketing_Head', 'Digital_Marketing_Head'), ('Team_Lead', 'Team_Lead'), ('Executive', 'Executive'), ('Data_Manager', 'Data_Manager'), ('Telecaller', 'Telecaller')], max_length=50, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('active_status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentRegister_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('active_status', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='digitalmarketing.businessregister_details')),
            ],
            options={
                'db_table': 'department_register_details',
            },
        ),
        migrations.CreateModel(
            name='DesignationRegister_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dashboard_id', models.CharField(blank=True, choices=[('Digital_Marketing_Head', 'Digital_Marketing_Head'), ('Team_Lead', 'Team_Lead'), ('Executive', 'Executive'), ('Data_Manager', 'Data_Manager'), ('Telecaller', 'Telecaller')], max_length=50, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('active_status', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='digitalmarketing.businessregister_details')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='digitalmarketing.departmentregister_details')),
            ],
            options={
                'db_table': 'designation_register_details',
            },
        ),
        migrations.AddField(
            model_name='businessregister_details',
            name='distributor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='digitalmarketing.distributorregister_details'),
        ),
        migrations.CreateModel(
            name='EmployeeRegister_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('employee_code', models.CharField(blank=True, default='EMP001', max_length=255, null=True)),
                ('contact_number', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('profile_picture', models.ImageField(default='', upload_to='profiles')),
                ('documents', models.FileField(default='', upload_to='employee_files')),
                ('address_line1', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('address_line2', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('address_line3', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('pin', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('location', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('district', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('state', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('active_status', models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending')], default='Pending', max_length=50, null=True)),
                ('verification_status', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='digitalmarketing.businessregister_details')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='digitalmarketing.departmentregister_details')),
                ('designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='digitalmarketing.designationregister_details')),
                ('login', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='digitalmarketing.logregister_details')),
            ],
            options={
                'db_table': 'employee_register_details',
            },
        ),
        migrations.CreateModel(
            name='EmployeeLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('leave_type', models.CharField(blank=True, max_length=255, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('number_of_days', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('applied_date', models.DateField(auto_now_add=True, null=True)),
                ('status_changed_date', models.DateField(blank=True, null=True)),
                ('request_file', models.FileField(blank=True, null=True, upload_to='leave/files/')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='digitalmarketing.employeeregister_details')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compaint_head', models.CharField(blank=True, max_length=255, null=True)),
                ('compaint_content', models.TextField(blank=True, null=True)),
                ('complaint_date', models.DateField(auto_now_add=True, null=True)),
                ('action', models.TextField(blank=True, null=True)),
                ('action_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='digitalmarketing.employeeregister_details')),
            ],
        ),
        migrations.CreateModel(
            name='AllocationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocate_status', models.IntegerField(default=0)),
                ('allocation_date', models.DateField(auto_now_add=True, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='digitalmarketing.employeeregister_details')),
                ('team_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allocated_employees', to='digitalmarketing.employeeregister_details')),
            ],
        ),
        migrations.CreateModel(
            name='ActionTaken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_id', models.IntegerField(default=0)),
                ('from_name', models.CharField(blank=True, max_length=255, null=True)),
                ('act_reason', models.TextField(blank=True, null=True)),
                ('act_head', models.CharField(blank=True, max_length=255, null=True)),
                ('act_content', models.TextField(blank=True, null=True)),
                ('action_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='digitalmarketing.employeeregister_details')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('schedule_head', models.CharField(blank=True, max_length=255, null=True)),
                ('todo_content', models.TextField(blank=True, null=True)),
                ('log_time', models.TimeField(auto_now_add=True, null=True)),
                ('schedule_date', models.DateField(blank=True, null=True)),
                ('schedule_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='digitalmarketing.employeeregister_details')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_id', models.IntegerField(default=0)),
                ('from_name', models.CharField(blank=True, max_length=255, null=True)),
                ('feedback_content', models.TextField(blank=True, null=True)),
                ('feedback_date', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='digitalmarketing.employeeregister_details')),
            ],
        ),
        migrations.AddField(
            model_name='distributorregister_details',
            name='login',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='digitalmarketing.logregister_details'),
        ),
        migrations.AddField(
            model_name='businessregister_details',
            name='login',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='digitalmarketing.logregister_details'),
        ),
    ]
