# Generated by Django 5.1.6 on 2025-05-14 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalmarketing', '0002_clientregister_clienttask_register_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadCateogry_TeamAllocate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('target', models.IntegerField(default=0)),
                ('target_achieved', models.IntegerField(default=0)),
                ('file', models.FileField(blank=True, null=True, upload_to='work/files')),
                ('progress', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('lead_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='digitalmarketing.leadcategory_register')),
                ('team_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='digitalmarketing.employeeregister_details')),
            ],
        ),
        migrations.CreateModel(
            name='TaskAssign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='work/files')),
                ('progress', models.IntegerField(default=0)),
                ('allocate_date', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('target', models.IntegerField(default=0)),
                ('target_achieved', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('accept_status', models.IntegerField(default=0)),
                ('accept_date', models.DateField(blank=True, null=True)),
                ('type', models.IntegerField(default=0)),
                ('client_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='digitalmarketing.clienttask_register')),
                ('executive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='digitalmarketing.employeeregister_details')),
            ],
        ),
        migrations.CreateModel(
            name='LeadCategory_Assign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('target', models.IntegerField(default=0)),
                ('target_achieved', models.IntegerField(default=0)),
                ('file', models.FileField(blank=True, null=True, upload_to='work/files')),
                ('progress', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('executive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='digitalmarketing.employeeregister_details')),
                ('team_allocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='digitalmarketing.leadcateogry_teamallocate')),
                ('task_assign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='digitalmarketing.taskassign')),
            ],
        ),
        migrations.CreateModel(
            name='WorkAssign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='work/files')),
                ('progress', models.IntegerField(default=0)),
                ('assign_date', models.DateField(auto_now=True, null=True)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.IntegerField(default=0)),
                ('assign_type', models.IntegerField(default=0)),
                ('target', models.IntegerField(default=0)),
                ('target_achieved', models.IntegerField(default=0)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='digitalmarketing.clientregister')),
                ('client_task', models.ManyToManyField(related_name='task_allocated', to='digitalmarketing.clienttask_register')),
                ('co_workers', models.ManyToManyField(related_name='co_works_allocated', to='digitalmarketing.employeeregister_details')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='digitalmarketing.businessregister_details')),
                ('team_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allocated_tl', to='digitalmarketing.employeeregister_details')),
                ('work_register', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='digitalmarketing.workregister')),
            ],
        ),
        migrations.AddField(
            model_name='taskassign',
            name='work_assign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='digitalmarketing.workassign'),
        ),
        migrations.AddField(
            model_name='leadcateogry_teamallocate',
            name='work_assign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='digitalmarketing.workassign'),
        ),
    ]
