# Generated by Django 5.1.6 on 2025-05-16 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalmarketing', '0003_leadcateogry_teamallocate_taskassign_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workassign',
            name='criteria',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workassign',
            name='facebook_target',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workassign',
            name='instagram_target',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workassign',
            name='is_facebook',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workassign',
            name='is_instagram',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workassign',
            name='is_x',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workassign',
            name='x_target',
            field=models.IntegerField(default=0),
        ),
    ]
