# Generated by Django 5.1.6 on 2025-05-21 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalmarketing', '0004_workassign_criteria_workassign_facebook_target_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadcateogry_teamallocate',
            name='accept_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workassign',
            name='accept_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
