# Generated by Django 5.1.6 on 2025-05-21 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalmarketing', '0005_leadcateogry_teamallocate_accept_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workassign',
            name='assign_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
