# Generated by Django 5.1.6 on 2025-05-21 10:55

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalmarketing', '0006_alter_workassign_assign_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workassign',
            name='assign_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.CreateModel(
            name='TaskDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collect_date', models.DateField(auto_now=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.JSONField(blank=True, default=list)),
                ('target', models.IntegerField(default=0)),
                ('verified_target', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('task_assign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='digitalmarketing.taskassign')),
            ],
        ),
    ]
