# Generated by Django 5.1.6 on 2025-05-22 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalmarketing', '0007_alter_workassign_assign_date_taskdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskdetails',
            name='achieved_target',
            field=models.IntegerField(default=0),
        ),
    ]
