# Generated by Django 5.1.6 on 2025-05-25 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalmarketing', '0009_alter_taskdetails_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskDetails_tl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_category', models.BooleanField(default=False)),
                ('collect_date', models.DateField(auto_now=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='daily_work/files/')),
                ('target', models.IntegerField(default=0)),
                ('achieved_target', models.IntegerField(default=0)),
                ('verified_target', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('category_assign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tl_category_details', to='digitalmarketing.leadcateogry_teamallocate')),
                ('work_assign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tl_task_details', to='digitalmarketing.workassign')),
            ],
        ),
    ]
