# Generated by Django 5.1.6 on 2025-05-26 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalmarketing', '0010_taskdetails_tl'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskdetails',
            name='category_assign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='digitalmarketing.leadcateogry_teamallocate'),
        ),
        migrations.AddField(
            model_name='taskdetails',
            name='is_category',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taskdetails',
            name='work_assign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='digitalmarketing.workassign'),
        ),
    ]
