# Generated by Django 5.1.6 on 2025-05-31 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalmarketing', '0011_taskdetails_category_assign_taskdetails_is_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('added_date', models.DateField(auto_now_add=True, null=True)),
                ('added_time', models.TimeField(auto_now_add=True, null=True)),
                ('waste_data', models.IntegerField(default=0)),
                ('waste_data_reason', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(default=0)),
                ('transfer_date', models.DateField(auto_now_add=True, null=True)),
                ('transfer_status', models.IntegerField(default=0)),
                ('incomplete_status', models.IntegerField(default=0)),
                ('target_update_status', models.IntegerField(default=0)),
                ('repeated_status', models.IntegerField(default=0)),
                ('collected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='digitalmarketing.employeeregister_details')),
                ('lead_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='digitalmarketing.leadcategory_register')),
                ('task_assign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='digitalmarketing.taskassign')),
                ('work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='digitalmarketing.workregister')),
            ],
        ),
        migrations.CreateModel(
            name='LeadDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(blank=True, max_length=255, null=True)),
                ('field_data', models.CharField(blank=True, max_length=855, null=True)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='digitalmarketing.leads')),
            ],
        ),
        migrations.DeleteModel(
            name='TaskDetails_tl',
        ),
    ]
