# Generated by Django 5.1.6 on 2025-06-03 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalmarketing', '0012_leads_leaddetails_delete_taskdetails_tl'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=20)),
                ('achieved_text', models.TextField()),
                ('urls', models.TextField()),
                ('screenshots', models.FileField(upload_to='uploads/social/screenshots/')),
                ('remarks', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_promotions', to='digitalmarketing.taskdetails')),
            ],
        ),
    ]
