# Generated by Django 5.1.6 on 2025-06-04 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalmarketing', '0013_socialmediapromotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediapromotion',
            name='category_assign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='digitalmarketing.leadcateogry_teamallocate'),
        ),
        migrations.AddField(
            model_name='socialmediapromotion',
            name='work_assign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='digitalmarketing.workassign'),
        ),
        migrations.AlterField(
            model_name='socialmediapromotion',
            name='task_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_promotions', to='digitalmarketing.taskdetails'),
        ),
    ]
