# Generated by Django 5.1.6 on 2025-06-05 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalmarketing', '0014_socialmediapromotion_category_assign_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_date', models.DateField(auto_now_add=True, null=True)),
                ('used_count', models.IntegerField(default=0)),
                ('lead_allocate_status', models.IntegerField(default=0)),
                ('current_status', models.CharField(default='No update', max_length=150)),
                ('allocated_date', models.DateField(blank=True, null=True)),
                ('followup_date', models.DateField(blank=True, null=True)),
                ('lead_status', models.CharField(default='Not Attended', max_length=150)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='digitalmarketing.leads')),
            ],
        ),
        migrations.CreateModel(
            name='PlatformData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_add_date', models.DateField(auto_now_add=True, null=True)),
                ('platform_name', models.CharField(default='', max_length=150)),
                ('platform_data_count', models.IntegerField(default=0)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='digitalmarketing.businessregister_details')),
            ],
        ),
        migrations.CreateModel(
            name='Platforms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('platform_name', models.CharField(default='', max_length=150)),
                ('platform_total_count', models.IntegerField(default=0)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='digitalmarketing.businessregister_details')),
            ],
        ),
    ]
