# Generated by Django 5.1.6 on 2025-06-14 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalmarketing', '0015_databank_platformdata_platforms'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadAssignedToTC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('reason', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('assign_date', models.DateField(auto_now_add=True, null=True)),
                ('allocate_time', models.TimeField(default='00:00:00')),
                ('update_date', models.DateField(blank=True, null=True)),
                ('next_update_date', models.DateField(blank=True, null=True)),
                ('update_action', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='digitalmarketing.clientregister')),
                ('databank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='digitalmarketing.databank')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='digitalmarketing.leads')),
                ('telecaller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='digitalmarketing.employeeregister_details')),
            ],
        ),
    ]
