# Generated by Django 5.1.6 on 2025-06-17 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalmarketing', '0016_leadassignedtotc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databank',
            name='lead_status',
            field=models.CharField(default='Not Allocated', max_length=150),
        ),
    ]
