# Generated by Django 5.1.6 on 2025-06-17 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalmarketing', '0017_alter_databank_lead_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadassignedtotc',
            name='allocate_time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
