# Generated by Django 5.1.6 on 2025-06-17 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalmarketing', '0018_alter_leadassignedtotc_allocate_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowupStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(default='', max_length=150)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='digitalmarketing.businessregister_details')),
            ],
        ),
    ]
