# Generated by Django 5.1.6 on 2025-06-20 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalmarketing', '0021_alter_leadassignedtotc_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowupDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_date', models.DateField(auto_now_add=True, null=True)),
                ('response', models.TextField(blank=True, default='', null=True)),
                ('next_followup_date', models.DateField(blank=True, null=True)),
                ('response_status', models.CharField(default='', max_length=150)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='digitalmarketing.businessregister_details')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='digitalmarketing.leads')),
                ('telecaller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='digitalmarketing.employeeregister_details')),
            ],
        ),
        migrations.CreateModel(
            name='FollowupHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_date', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True, default='', null=True)),
                ('final_status', models.CharField(default='', max_length=150)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='digitalmarketing.businessregister_details')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='digitalmarketing.leads')),
                ('telecaller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='digitalmarketing.employeeregister_details')),
            ],
        ),
        migrations.CreateModel(
            name='LeadCallRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField(auto_now_add=True, null=True)),
                ('record_time', models.TimeField(auto_now_add=True, null=True)),
                ('record_file', models.FileField(blank=True, null=True, upload_to='record/')),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='digitalmarketing.leadassignedtotc')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='digitalmarketing.leads')),
            ],
        ),
        migrations.CreateModel(
            name='WasteLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waste_marked_date', models.DateField(auto_now_add=True, null=True)),
                ('reason', models.TextField(blank=True, default='')),
                ('status', models.IntegerField(default=0)),
                ('head_reason', models.TextField(blank=True, default='')),
                ('confirmation', models.IntegerField(default=0)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='digitalmarketing.leadassignedtotc')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='digitalmarketing.clientregister')),
                ('databank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='digitalmarketing.databank')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='digitalmarketing.leads')),
                ('telecaller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='digitalmarketing.employeeregister_details')),
            ],
        ),
    ]
