# Generated by Django 5.0.6 on 2025-04-29 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogRegister_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_username', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('log_password', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('log_date', models.DateField(auto_now_add=True)),
                ('log_time', models.TimeField(auto_now_add=True)),
                ('position', models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Digital_Marketing_Head', 'Digital_Marketing_Head'), ('Team_Lead', 'Team_Lead'), ('Executive', 'Executive'), ('Data_Manager', 'Data_Manager'), ('Telecaller', 'Telecaller')], max_length=50, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('active_status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DistributorRegister_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('contact_no', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('agencies', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('profile', models.FileField(blank=True, null=True, upload_to='profiles/')),
                ('file', models.FileField(blank=True, null=True, upload_to='employee_files/')),
                ('address1', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('address2', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('address3', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('pin', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('location', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('district', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('state', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('active_status', models.BooleanField(default=False)),
                ('reg_date', models.DateField(auto_now_add=True)),
                ('login', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.logregister_details')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessRegister_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_fname', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('owner_lname', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('company_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('contact_number', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('logo', models.FileField(blank=True, null=True, upload_to='profiles/')),
                ('website', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('address_line1', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('address_line2', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('address_line3', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('pin', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('location', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('district', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('state', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('active_status', models.BooleanField(default=True)),
                ('reg_date', models.DateField(auto_now_add=True)),
                ('company_code', models.CharField(default='COMID001', max_length=150)),
                ('distributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.distributorregister_details')),
                ('login', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.logregister_details')),
            ],
        ),
    ]
