# Generated by Django 3.2.25 on 2025-05-05 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentRegister_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('active_status', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.businessregister_details')),
            ],
            options={
                'db_table': 'department_register_details',
            },
        ),
        migrations.CreateModel(
            name='DesignationRegister_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dashboard_id', models.CharField(blank=True, choices=[('Digital_Marketing_Head', 'Digital_Marketing_Head'), ('Team_Lead', 'Team_Lead'), ('Executive', 'Executive'), ('Data_Manager', 'Data_Manager'), ('Telecaller', 'Telecaller')], max_length=50, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('active_status', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.businessregister_details')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.departmentregister_details')),
            ],
            options={
                'db_table': 'designation_register_details',
            },
        ),
        migrations.CreateModel(
            name='EmployeeRegister_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('employee_code', models.CharField(blank=True, default='EMP001', max_length=255, null=True)),
                ('contact_number', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('profile_picture', models.ImageField(default='', upload_to='profiles')),
                ('documents', models.FileField(default='', upload_to='employee_files')),
                ('address_line1', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('address_line2', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('address_line3', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('pin', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('location', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('district', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('state', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('active_status', models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending')], default='Pending', max_length=50, null=True)),
                ('verification_status', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.businessregister_details')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.departmentregister_details')),
                ('designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.designationregister_details')),
                ('login', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.logregister_details')),
            ],
            options={
                'db_table': 'employee_register_details',
            },
        ),
    ]
